# Generated by Django 3.2.9 on 2021-12-29 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('location', models.CharField(max_length=50, verbose_name='Город')),
                ('logo', models.ImageField(
                    default='https://place-hold.it/100x60',
                    upload_to='company_images',
                    verbose_name='Логотип')
                 ),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('employee_count', models.PositiveSmallIntegerField(verbose_name='Количество сотрудников')),
                ('owner', models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Владелец')
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=50, verbose_name='Название специализации')),
                ('picture', models.ImageField(
                    default='https://place-hold.it/100x60',
                    upload_to='specialties_images',
                    verbose_name='Картинка')
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('skills', models.CharField(max_length=255, verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Текст')),
                ('salary_min', models.PositiveIntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликованно')),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vacancies', to='core.company',
                    verbose_name='Компания')
                 ),
                ('specialty', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vacancies', to='core.specialty',
                    verbose_name='Специальность')
                 ),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('status', models.CharField(
                    choices=[
                        ('0', 'Не ищу работу'),
                        ('1', 'Рассматриваю предложения'),
                        ('2', 'Ищу работу')
                    ],
                    default=None,
                    max_length=50,
                    verbose_name='Статус')
                 ),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('grade', models.CharField(choices=[
                    ('0', 'Стажер'),
                    ('1', 'Джуниор'),
                    ('2', 'Мидл'),
                    ('3', 'Сеньор'), ('4', 'Лид')
                ],
                    default=None,
                    max_length=50,
                    verbose_name='Квалификация')
                 ),
                ('photo', models.ImageField(
                    default='https://place-hold.it/100x60',
                    upload_to='user_images',
                    verbose_name='Фотография')
                 ),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('experience', models.TextField(null=True, verbose_name='Опыт работы')),
                ('description', models.TextField(null=True, verbose_name='О себе')),
                ('portfolio', models.CharField(max_length=100, verbose_name='Портфолио')),
                ('phone', models.CharField(
                    blank=True,
                    max_length=17,
                    validators=[django.core.validators.RegexValidator(
                        message="Телефонный номер должен быть в формате: '+999999999'", regex='^\\+?1?\\d{9,15}$')],
                    verbose_name='Телефон ')),
                ('specialty', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='resume',
                    to='core.specialty',
                    verbose_name='Специальность')
                 ),
                ('user', models.OneToOneField(blank=True,
                                              null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL,
                                              verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=50, verbose_name='Имя')),
                ('written_phone', models.CharField(
                    blank=True,
                    max_length=17,
                    validators=[
                        django.core.validators.RegexValidator(
                            message="Phone number must be entered in the format: '+999999999'",
                            regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон ')
                 ),
                ('written_cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='applications',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Пользователь')
                 ),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='applications',
                                              to='core.vacancy',
                                              verbose_name='Вакансия')
                 ),
            ],
        ),
    ]
